plugins {
	id 'java'
	id "com.github.johnrengelman.shadow" version "8.1.1"
}

apply plugin: 'idea'

group = "chrisliebaer"
version = "0.3"

tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}

repositories {
	mavenLocal()
	mavenCentral()
	jcenter()

	maven {
		url "https://repo.papermc.io/repository/maven-public/"
	}

	maven {
		url "https://repo.dmulloy2.net/nexus/repository/public/"
	}

	maven {
		url "https://repo.codemc.org/repository/maven-public/"
	}
	maven { url "https://maven.enginehub.org/repo/" }

}

dependencies {
	compileOnly "org.projectlombok:lombok:1.18.30"
	annotationProcessor "org.projectlombok:lombok:1.18.30"

	compileOnly 'io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT'
	compileOnly group: "com.comphenix.protocol", name: "ProtocolLib", version: "5.3.0"
	compileOnly 'org.jetbrains:annotations:17.0.0'
	compileOnly 'de.tr7zw:item-nbt-api-plugin:2.12.2'
	compileOnly 'com.sk89q.worldguard:worldguard-bukkit:7.0.9'

	testImplementation 'io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT'
	testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.9.2'
}

test {
	useJUnitPlatform()
}

shadowJar {
	archiveFileName = 'CommandBlOp-foxford-' + project.version.toString() + '.jar';
}

artifacts {
	shadowJar;
}
